### PR TITLE
Force C collation when finding test functions

### PR DESCRIPTION
**Pull request by decibel**

### CODE REVIEW

**Comment by theory** [comment]
Would you also update the patch files in combat to remove that clause on 9.0 and earlier?

**Comment by decibel** [comment]
"in combat"?

BTW, everything prior to 8.4 currently fails due to lack of support for 
WITH: https://travis-ci.org/decibel/pgtap/builds/166535262

How do you normally go about maintaining the compat patches? Manually 
apply, copy file, make necessary edits, create new patch?

**Comment by theory** [comment]
Pfft, fucking *everything* is [failing](https://travis-ci.org/theory/pgtap) right now.

Yeah, I usually end up spending a day or two before release working backward over releases and updating the patch files. It's a PITA, honestly.

**Comment by theory** [comment]
Sorry, I meant `compat`. Stupid autocorrect.

**Comment by decibel** [comment]
On 10/10/16 6:06 PM, David E. Wheeler wrote:
> Pfft, fucking /everything/ is failing
> <https://travis-ci.org/theory/pgtap> right now.

Derp. Fixed. (Though, one test is failing because I don't have isn 
installed, which pgxn can't even find...)

> Yeah, I usually end up spending a day or two before release working
> backward over releases and updating the patch files. It's a PITA, honestly.

Are you talking the upgrade files or compat?

**Comment by theory** [comment]
I forgot about the upgrade files, but both need to be done.

**Comment by decibel** [comment]
Ok, clean build with compat. Lets get this pulled in and I can do an upgrade script once we figure out if there's anything else going into this version.

**Comment by decibel** [comment]
Ok, clean build with compat. Lets get this pulled in and I can do an upgrade script once we figure out if there's anything else going into this version.

**Pull request closed without merging**
