### PR TITLE
Add is_indexed functionnality

### PR DESCRIPTION
**Pull request by rodo**
Ref #51 

I didn't write `isnt_indexed` as it don't make sense for me. What do you think @keithf4 ?
I looked for support expression too in place of `column` but didn't find how to do it, if I find an idea in future I'll do it.

### CODE REVIEW

**Comment by keithf4** [comment]
If Dave's happy with it, I'm happy with it :)

**Comment by theory** [comment]
Does this implementation only use column names, and not expressions? Or are expressions supported as well?

IOW, is this just like `has_index()`, but without requiring an index name?

**Comment by theory** [comment]
Merged in 1f0c4b2e5e4667d5554e33cc15cdf2ea816b55fe...fb203a7bc1364884dff363a73d8b35a2ccdff0da. Still want to flesh out the docs, though, especially the relationship to `has_index()`.

**Comment by theory** [comment]
@rodo: Could you answer my questions from a couple comments up? Thanks!

**Comment by rodo** [comment]
Sorry @theory I thought you find the answer as you closed the PR, anyway no **expression are not supported** only column name and array of column name.
Yes it's like `has_index` without indexname, some ORM like the one uses in Django generate index name like `app_foobar_5369a83d` when you index the column `bar` on table `app_foobar`, so it's better to check if the right column are indexed than rely on the index name, because index naming change between Django version too :-)

**Comment by theory** [comment]
Okay. Is there any reason why it shouldn't also support expressions?

**Comment by rodo** [comment]
No any good reason, it's just as I said previously, I don't find how to do it :-)

**Comment by pmonster** [comment]
Hello (newbe here) - for column expressions, you can find the expression for an existing  index from select pg_get_indexdef('indexname'::regclass, 1 , true), where 1 is the column position

**Pull request closed without merging**
