### PR TITLE
add non-description versions of col_is_pk with schema

### PR DESCRIPTION
**Pull request by chamini2**

### CODE REVIEW

**Comment by chamini2** [comment]
Tests are failing for a strange reason in some environments

**Comment by chamini2** [comment]
I just realized this has already been done in #178, but I did not use the `DEFAULT` keyword. Maybe you can take a look here? If this is merged I intend to add more functions' missing variants.

**Comment by nasbyj** [comment]
Please merge master and see if that fixes things. Also, please see the test that's failing in #178; we need to ensure that the (table, column) and (table, column, description) variations continue to work without requiring casting.

**Comment by nasbyj** [comment]
(BTW, if you allow admins to modify your pull request I can try and do the merge for you).

**Comment by chamini2** [comment]
Hey @nasbyj, I tried by just rebasing but it seems my PR has issues now. Maybe you can take a look at it. I have the `Allow edits from maintainers` enabled. I will add you to my repository where the branch is being updated so you can push there.

**Comment by theory** [comment]
> (BTW, if you allow admins to modify your pull request I can try and do the merge for you).

Is this something you'd still like to do, Jim?

**Comment by theory** [comment]
Merged in 8f4a881, thank you!

**Pull request closed without merging**
