### PR TITLE
Change plan() to accept bigint

### PR DESCRIPTION
**Pull request by decibel**
WIP! See email on list for rational.

### CODE REVIEW

**Comment by theory** [comment]
What's the status of this PR, @decibel?

**Comment by decibel** [comment]
AFAIK it's ready to go.

**Comment by theory** [comment]
I think it needs an entry in the upgrade script, no?

**Comment by decibel** [comment]
Since this is missing entries in the upgrade script and I have a post 0.98.0 branch that adds tests for that, I think this should wait.

**Comment by theory** [comment]
I am hard-pressed to imagine a situation in which someone would need more than `2,147,483,647` assertions in a single test script. If one needs to run so many variations, maybe block them into 1m records per assertion or break them up into separate tests.

**Pull request closed without merging**
