### PR TITLE
More travis support

### PR DESCRIPTION
**Pull request by decibel**

### CODE REVIEW

**Comment by decibel** [comment]
Though it's still undecided where we're going to draw the line at supporting old versions, I'd like to get this merged real soon to enable testing of other PR's. Unless I hear an objection I'll pull this in in the next few hours.

BTW, the only possible downside I see here is getting rid of the WITH in `_is_indexed()` will change the query plan, but IMHO it shouldn't have been there to begin with, because it's a fence.

**Comment by theory** [comment]
Can you merge it without those interim merge requests? Maybe do a squash merge.

**Comment by decibel** [comment]
Yeah, I messed up my master, so I've been rebasing stuff before merging.

**Comment by theory** [comment]
Ah. Here's how to [reset your master to upstream](http://stackoverflow.com/a/8135023/79202).

**Comment by decibel** [comment]
Yeah, I did it the hard way by just deleting my master branch and 
re-creating it from upstream. I'll be more careful about introducing 
noise in the future.

**Comment by decibel** [comment]
I diff of just the backwards-compatibility changes is https://github.com/decibel/pgtap/compare/master...decibel:more_travis

**Comment by theory** [comment]
You'll need to copy the SQL changes to the upgrade script.

**Comment by decibel** [comment]
Wow, not sure how I screwed that up... good catch. Fixed.

**Comment by theory** [comment]
We should get the tests passing on 8.2 and 8.3, yes?

**Comment by decibel** [comment]
Just committed that fix.

**Comment by theory** [comment]
Okay, trying to sort out all the PRs and decide what should go into v0.98. Should this one, @decibel?

**Comment by decibel** [comment]
IIRC the plan is 0.98 is the last version that will support PG < 9.1, so yes, we should merge this in.

**Comment by theory** [comment]
Er, kind of looks like it's already merged, no? The "Files changed" tab of this PR shows no changes.

**Comment by decibel** [comment]
Yup, looks like this was merged at some point.

**Pull request closed without merging**
