### PR TITLE
Add 9.6 to travis

### PR DESCRIPTION
**Pull request by decibel**

### CODE REVIEW

**Comment by decibel** [comment]
@theory there's 3 failures due to changes in context messaging (see https://travis-ci.org/theory/pgtap/jobs/169088857). Is the best way to handle those to just add more pg_version_num() conditional stuff to the tests? Is there anything else we'd need to do?

**Comment by theory** [comment]
You could add variant expected scripts, but it's kind of a PITA. `pg_version_num()` variants are probably the most maintainable way to go. I typically end up doing a bunch of that sort of tweaking when I prep a release.

**Comment by decibel** [comment]
Good news... now that I've got schedules working it's pretty easy to 
configure what tests should and shouldn't run. This only works at the 
wholesale test level, which I don't think helps the 9.6 stuff, but I 
think it'll make some other tests simpler.

**Comment by decibel** [comment]
This was handled as part of fixing 8.2-8.4.

**Pull request closed without merging**
