### PR TITLE
Add has extension

### PR DESCRIPTION
**Pull request by rodo**
Add functions to test if an extension is deployed into a database.
This PR replaces #100 
I'll do another PR for extension_version_is once I undertsand how to generate files in `compat/` directory

### CODE REVIEW

**Comment by rodo** [comment]
@theory I've found and understood how to generate files in `compat/` this time tests on Travis are green.

**Comment by rodo** [comment]
@theory is there anything you are waiting from me on this PR ?

**Comment by theory** [comment]
Just time and TUITs. Does it need rebasing? I can't remember.

**Comment by rodo** [comment]
No problem, no you can merge it as is, I take care of doing cherry pick mergeable PR :)

**Comment by dachary** [comment]
@rodo I'm interested in theses changes, are they abandoned or are you still working on them ?

**Comment by rodo** [comment]
@dachary yes the job is done, just waiting for @theory too merge the PR, may be soon.

**Comment by theory** [comment]
I think the upgrade script needs to be modified, too.

**Comment by decibel** [comment]
My intention was to look carefully at `git diff 0.97` to build/finish the upgrade script.

**Comment by rodo** [comment]
Thank you @decibel for the merge \o/

**Pull request merged**
