### PR TITLE
Re-qualify argument type names to be immune of search_path

### LINKED ISSUE #179: [REGRESSION] has_function fails to recognize fully-qualified type names in 0.99 (worked in 0.97)
Against a PostgreSQL versioned 9.6, pgtap 0.99.0 fails a test that 0.97.0 passes.
The test is:
> SELECT has_function('bde', 'bde_get_app_specific', ARRAY['bde.crs_appellation', 'character']);

The function takes a complex type being a table under the `bde` schema.
For testing, the table and function are defined in http://github.com/linz/linz-bde-schema

### PR DESCRIPTION
**Pull request by strk**
Closes #179

NOTE: at the moment a test is failing but I don't read enough output
from the failure to tell why (needs more work)

### CODE REVIEW

**Comment by strk** [comment]
I've now also added the test showing the need for the change. Not sure this is the right way to add tests because it generates a big patch for `tests/expected/functap.out` due to inserting the test in the middle rather than at the end, please advice if I should change anything in that reguard

**Comment by theory** [comment]
Thanks for this, @strk. Unfortunately, the problem with making a change like this is that casting a string to a `regtype` throws an error if the type doesn't exist:

``` sql
select 'x'::regtype;
ERROR:  type "x" does not exist
```

And we don't want the test function to throw an error if the type doesn't exist. I think the correct solution is for the tester not to schema-qualify the argument types if those types are in the search path.

I like the idea, in general, of allowing the schema-qualification, but we'd need some way to suppress the error to make it work. Could maybe add a function that does it, but it starts to feel like a lot of work for something easily fixed in the tests themselves. Thoughts?

**Comment by theory** [comment]
I did a little experimentation implementing such a function, to be called like this:

``` sql
         WHERE schema = $1
           AND name   = $2
           AND args = _funkargs($3)
```

This variant works as far back as 8.4:

``` sql
CREATE OR REPLACE FUNCTION _funkargs ( NAME[] )
RETURNS TEXT AS $$
BEGIN
    RETURN array_to_string($1::regtype[], ',');
EXCEPTION WHEN undefined_object THEN
    RETURN array_to_string($1, ',');
END;
$$ LANGUAGE PLPGSQL;
```

If I change the argument to `text[]`, it works on 8.3, too. But it breaks on 8.2 for two reasons. One is that there is no cast from `text[]` to `regtype[]`. This variant works around that issue:

``` sql
CREATE OR REPLACE FUNCTION _funkargs ( TEXT[] )
RETURNS TEXT AS $$
BEGIN
    RETURN array_to_string(ARRAY(
        SELECT $1[i]::regtype
          FROM generate_series(1, array_upper($1, 1)) s(i)
         ORDER BY i
    ), ',');
EXCEPTION WHEN undefined_object THEN
    RETURN array_to_string($1, ',');
END;
$$ LANGUAGE PLPGSQL;
```

Except that there is no cast from `text` to `regtype`, either.

So I'm inclined not to add the function right now, until we drop support for these older versions of PostgreSQL.

**Comment by theory** [comment]
Okay, I worked it out. Merged in 3c98e8d. Thank you!

**Pull request closed without merging**
