### PR TITLE
Make description optional for col_(is|not)_null(schema, ...)

### PR DESCRIPTION
**Pull request by decibel**
Description was optional for non-schema qualified version; is now optional for schema qualified as well. To make use of that you do need to make certain the column argument is typed as a name.

### CODE REVIEW

**Comment by theory** [comment]
Should we rebase this one and add it to v0.98, @decibel?

**Comment by decibel** [comment]
Either way is fine for this one, since it doesn't touch make.

**Comment by theory** [comment]
Feel free to make the necessary updates to the docs and merge, @decibel.

**Comment by decibel** [comment]
Since this is missing entries in the upgrade script and I have a post 0.98.0 branch that adds tests for that, I think this should wait.

**Comment by nasbyj** [comment]
Closed by #221

**Pull request closed without merging**
