### PR TITLE
Add negation functions isnt_aggregate() and isnt_definer()

### PR DESCRIPTION
**Pull request by rodo**
This will fix the issue #38
Hope this time the PR is complete. @theory please fee free to request me some fix if you want to merge the RP directly.

### CODE REVIEW

**Comment by theory** [comment]
Looks great. My only suggestion is to put the negative versions immediate after the positive in the docs. So `isnt_definer()` should follow immediately after `is_definer()`.

You interested in having commit access, @rodo?

**Comment by rodo** [comment]
Totally agree with you, it was I've done, `is_definer()` doc ends at line 4923 and `isnt_definer()` doc starts at 4924. The same for `isnt_aggregate()`. I tried to do the same as you.

Doing PR in my onw repo suits my needs, it's up to you, thanks for your proposal.

**Comment by rodo** [comment]
Hi, @theory did you find time to review ?

**Comment by theory** [comment]
Nope. Still have a bunch of tabs open in my browser to get to eventually…

**Comment by decibel** [comment]
@rodo: please resolve conflicts.

**Comment by theory** [comment]
Holy crap, @decibel, this PR now has a lot of changes from other PRs. Probably need to rebase it on master.

**Pull request merged**
