### PR TITLE
Replace C parse_type() function with PL/pgSQL

### LINKED ISSUE #328: No longer installable by non-superuser
Version 1.3.1 introduced a language c function `parse_type` ([see here](https://github.com/theory/pgtap/blob/main/sql/pgtap--1.3.0--1.3.1.sql#L1-L4)).

The control file still defines `superuser` as false ([see here](https://github.com/theory/pgtap/blob/main/pgtap.control#L7)). However, since this recent inclusion it is no longer possible to create the extension as a non-superuser.

Repro steps on 1.3.1:
```
postgres=> \c postgres postgres 
You are now connected to database "postgres" as user "postgres".

postgres=# GRANT ALL ON SCHEMA public TO alice;
GRANT

postgres=# \c postgres alice
You are now connected to database "postgres" as user "alice".

postgres=> CREATE EXTENSION pgtap;
ERROR:  permission denied for language c
```

### PR DESCRIPTION
**Pull request by theory**
The C code cause a number of challenges, including the requirement for a superuser to install the extension, and would require a fair bit of refactoring to abide by [secure design principals]. It also makes installation difficult on Windows, and would likely be rejected by organizations like AWS that tend to balk at C code.

So delete the `parse_type()` function and all the C code added in 4ec32e7 and rewrite the `format_type_string()` function based on the prototype that @ewie developed in the comments of #315. By looking up the type output format function in the catalog, we're able to correctly output the data type with its full SQL name as before. The exception is interval types, which require the PostgreSQL grammar to parse the interval fields (`second`, `interval minute`, etc.) into a bitmask for the `typmod`. So require that they be specified exactly as PostgreSQL outputs them.

Fixes #328.

  [secure design principals]: https://www.postgresql.org/docs/current/extend-extensions.html#EXTEND-EXTENSIONS-SECURITY

### CODE REVIEW

**Comment by theory** [comment]
@ewie what do you think?

**Comment by ewie** [comment]
@theory, ah you already closed it! I just came home and wanted to review this. So no need to resolve `interval` in your opinion? Admittedly, it's a bit cumbersome to resolve the typemod for `interval`.

**Comment by theory** [comment]
Yeah, I wanted to get a release out. Holler if anything looks amiss, though.

I don't think so we need to handle intervals. I updated the docs to say they're required to be specified exactly, and if the `parse_type()` patch gets merged, I'll updated it for Postgres 17 and move this function to a patch for older versions.

**Comment by ewie** [comment]
Nah, it's good! I've missed the mentioning of the `interval` case in the changelog and docs.

**Comment by theory** [comment]
I looked into it briefly, but when I realized I couldn't think of a way to specify the type that wasn't exactly right other than white space, I decided not to worry about it.

**Pull request merged**
