### PR TITLE
Inheritance test

### PR DESCRIPTION
**Pull request by fluca1978**
This is my first contribution and an effort to implement test for inheritance among tables (see issue #152 ).
A new set of functions has been implemented:
- `has_inherited_tables` to check if a table has children (negated by `hasnt_inherited_tables`);
- `is_parent_of` to check if a table is a n-th parent of another one (negated by `isnt_parent_of`);
- `is_child_of` to check if a table is a n-th child of another one (negated by `isnt_child_of`).

Please note that the parent-child relationship is found running a recursive CTE (see `_parent` function) and this could limit the scope of application of these tests to older PostgreSQL versions to 8.4.

Documentation and tests updated.

### CODE REVIEW

**Comment by theory** [comment]
Thanks @fluca1978! Sadly, the [tests are failing](https://travis-ci.org/theory/pgtap/builds/436485154). :-(

**Comment by fluca1978** [comment]
I need a little help here: initially the test were failing because of the introduction of 'format', removed by commit 8dfbc22f6372d78f826015845cd0a3780170c58e, but looking at more recent versions of PostgreSQL, tests are failing due to something else:

```
--- 1,9 ----
  \unset ECHO
+ psql:sql/pgtap.sql:1165: ERROR:  type "quote_ident" does not exist
+ LINE 5: ...          'Table ' || quote_ident( $1 ) || '.' || quote_iden...
+                                                              ^
  1..270
! ERROR:  function has_index(unknown, unknown, unknown, unknown, unknown) does not exist
! LINE 4:     has_index( 'public', 'sometab', 'idx_hey', 'numb', 'what...
!             ^
! HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

which is something outside my scope. Looking at postgresql 8.4 the error is:
```

--- 1,10 ----
  \unset ECHO
+ psql:sql/pgtap.sql:1147: ERROR:  function format(unknown, name) does not exist
+ LINE 4:                   coalesce( $2, format( 'Table %I has childr...
+                                         ^
+ HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
  1..270
! ERROR:  function has_index(unknown, unknown, unknown, unknown, unknown) does not exist
! LINE 4:     has_index( 'public', 'sometab', 'idx_hey', 'numb', 'what...
!             ^
! HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
======================================================================
```

which refers to the usage of format remove by the last commit.
I'm a little confused here.

**Comment by fluca1978** [comment]
@theory sorry, is there a way to trigger again the tests? I think commit 8dfbc22f6372d78f826015845cd0a3780170c58e has fixed a few of such failures. Apparently my branch is up-to-date.

**Comment by theory** [comment]
I restarted [the build](
https://travis-ci.org/theory/pgtap/builds/436485154), @fluca1978.

**Comment by theory** [comment]
I pulled your branch and fixed the inheritance tests. All tests pass for me on 11beta4 with this diff:

``` diff
diff --git a/test/expected/inheritance.out b/test/expected/inheritance.out
index 2987b5ba..77ee597c 100644
--- a/test/expected/inheritance.out
+++ b/test/expected/inheritance.out
@@ -1,85 +1,19 @@
-1..84
-ok 1 - has_pk( schema, table, description ) should pass
-ok 2 - has_pk( schema, table, description ) should have the proper description
-ok 3 - has_pk( schema, table, description ) should have the proper diagnostics
-ok 4 - has_pk( hideschema, hidetable, description ) should pass
-ok 5 - has_pk( hideschema, hidetable, description ) should have the proper description
-ok 6 - has_pk( hideschema, hidetable, description ) should have the proper diagnostics
-ok 7 - has_pk( table, description ) should pass
-ok 8 - has_pk( table, description ) should have the proper description
-ok 9 - has_pk( table, description ) should have the proper diagnostics
-ok 10 - has_pk( hidetable, description ) fail should fail
-ok 11 - has_pk( hidetable, description ) fail should have the proper description
-ok 12 - has_pk( hidetable, description ) fail should have the proper diagnostics
-ok 13 - has_pk( table ) should pass
-ok 14 - has_pk( table ) should have the proper description
-ok 15 - has_pk( table ) should have the proper diagnostics
-ok 16 - has_pk( schema, table, description ) fail should fail
-ok 17 - has_pk( schema, table, description ) fail should have the proper description
-ok 18 - has_pk( schema, table, description ) fail should have the proper diagnostics
-ok 19 - has_pk( table, description ) fail should fail
-ok 20 - has_pk( table, description ) fail should have the proper description
-ok 21 - has_pk( table, description ) fail should have the proper diagnostics
-ok 22 - hasnt_pk( schema, table, description ) should fail
-ok 23 - hasnt_pk( schema, table, description ) should have the proper description
-ok 24 - hasnt_pk( schema, table, description ) should have the proper diagnostics
-ok 25 - hasnt_pk( table, description ) should fail
-ok 26 - hasnt_pk( table, description ) should have the proper description
-ok 27 - hasnt_pk( table, description ) should have the proper diagnostics
-ok 28 - hasnt_pk( table ) should fail
-ok 29 - hasnt_pk( table ) should have the proper description
-ok 30 - hasnt_pk( table ) should have the proper diagnostics
-ok 31 - hasnt_pk( schema, table, description ) pass should pass
-ok 32 - hasnt_pk( schema, table, description ) pass should have the proper description
-ok 33 - hasnt_pk( schema, table, description ) pass should have the proper diagnostics
-ok 34 - hasnt_pk( table, description ) pass should pass
-ok 35 - hasnt_pk( table, description ) pass should have the proper description
-ok 36 - hasnt_pk( table, description ) pass should have the proper diagnostics
-ok 37 - col_is_pk( schema, table, column, description ) should pass
-ok 38 - col_is_pk( schema, table, column, description ) should have the proper description
-ok 39 - col_is_pk( schema, table, column, description ) should have the proper diagnostics
-ok 40 - col_is_pk( table, column, description ) should pass
-ok 41 - col_is_pk( table, column, description ) should have the proper description
-ok 42 - col_is_pk( table, column, description ) should have the proper diagnostics
-ok 43 - col_is_pk( table, column ) should pass
-ok 44 - col_is_pk( table, column ) should have the proper description
-ok 45 - col_is_pk( table, column ) should have the proper diagnostics
-ok 46 - col_is_pk( schema, table, column, description ) fail should fail
-ok 47 - col_is_pk( schema, table, column, description ) fail should have the proper description
-ok 48 - col_is_pk( schema, table, column, description ) fail should have the proper diagnostics
-ok 49 - col_is_pk( table, column, description ) fail should fail
-ok 50 - col_is_pk( table, column, description ) fail should have the proper description
-ok 51 - col_is_pk( table, column, description ) fail should have the proper diagnostics
-ok 52 - col_is_pk( schema, table, column[], description ) should pass
-ok 53 - col_is_pk( schema, table, column[], description ) should have the proper description
-ok 54 - col_is_pk( schema, table, column[], description ) should have the proper diagnostics
-ok 55 - col_is_pk( table, column[], description ) should pass
-ok 56 - col_is_pk( table, column[], description ) should have the proper description
-ok 57 - col_is_pk( table, column[], description ) should have the proper diagnostics
-ok 58 - col_is_pk( table, column[] ) should pass
-ok 59 - col_is_pk( table, column[] ) should have the proper description
-ok 60 - col_is_pk( table, column[] ) should have the proper diagnostics
-ok 61 - col_isnt_pk( schema, table, column, description ) should fail
-ok 62 - col_isnt_pk( schema, table, column, description ) should have the proper description
-ok 63 - col_isnt_pk( schema, table, column, description ) should have the proper diagnostics
-ok 64 - col_isnt_pk( table, column, description ) should fail
-ok 65 - col_isnt_pk( table, column, description ) should have the proper description
-ok 66 - col_isnt_pk( table, column, description ) should have the proper diagnostics
-ok 67 - col_isnt_pk( table, column ) should fail
-ok 68 - col_isnt_pk( table, column ) should have the proper description
-ok 69 - col_isnt_pk( table, column ) should have the proper diagnostics
-ok 70 - col_isnt_pk( schema, table, column, description ) pass should pass
-ok 71 - col_isnt_pk( schema, table, column, description ) pass should have the proper description
-ok 72 - col_isnt_pk( schema, table, column, description ) pass should have the proper diagnostics
-ok 73 - col_isnt_pk( table, column, description ) pass should pass
-ok 74 - col_isnt_pk( table, column, description ) pass should have the proper description
-ok 75 - col_isnt_pk( table, column, description ) pass should have the proper diagnostics
-ok 76 - col_isnt_pk( schema, table, column[], description ) should pass
-ok 77 - col_isnt_pk( schema, table, column[], description ) should have the proper description
-ok 78 - col_isnt_pk( schema, table, column[], description ) should have the proper diagnostics
-ok 79 - col_isnt_pk( table, column[], description ) should pass
-ok 80 - col_isnt_pk( table, column[], description ) should have the proper description
-ok 81 - col_isnt_pk( table, column[], description ) should have the proper diagnostics
-ok 82 - col_isnt_pk( table, column[] ) should pass
-ok 83 - col_isnt_pk( table, column[] ) should have the proper description
-ok 84 - col_isnt_pk( table, column[] ) should have the proper diagnostics
+\unset ECHO
+1..17
+ok 1 - hide.h_parent is supposed to be parent of other tables should pass
+ok 2 - hide.h_child2 is not supposed to have children should pass
+ok 3 - public.parent is supposed to be parent of other tables should pass
+ok 4 - public.child2 is supposed not to have children should pass
+ok 5 - hide.h_parent direct is father of hide.h_child1 should pass
+ok 6 - hide.h_parent direct is father of hide.h_child1 should pass
+ok 7 - hide.h_child1 direct is father of hide.h_child2 should pass
+ok 8 - hide.h_parent is father of hide.h_child2 should pass
+ok 9 - child1 inherits from parent should pass
+ok 10 - hide.h_parent is not father of public.child1 should fail
+ok 11 - public.parent is not father of public.child1 should pass
+ok 12 - hide.h_parent is not father of public.child1 should pass
+ok 13 - parent is not father of public.child1 should fail
+ok 14 - parent is not child1 should pass
+ok 15 - child1 inherits from parent should fail
+ok 16 - hide.h_parent is not child of hide.h_child1 should pass
+ok 17 - hide.h_child1 inherits from hide.h_parent should fail
diff --git a/test/sql/inheritance.sql b/test/sql/inheritance.sql
index 0c0031ef..2cd0c910 100644
--- a/test/sql/inheritance.sql
+++ b/test/sql/inheritance.sql
@@ -1,7 +1,7 @@
---\unset ECHO
---\i test/setup.sql
-BEGIN;
+\unset ECHO
+\i test/setup.sql
 SELECT plan( 17 );
+SET client_min_messages = warning;
 
 -- Create inherited tables
 CREATE TABLE public.parent( id INT PRIMARY KEY );
@@ -14,7 +14,6 @@ CREATE TABLE hide.h_parent( id INT PRIMARY KEY );
 CREATE TABLE hide.h_child1( id INT PRIMARY KEY ) INHERITS ( hide.h_parent );
 CREATE TABLE hide.h_child2( id INT PRIMARY KEY ) INHERITS ( hide.h_child1 );
 
-
 -- test has_inhereted_tables
 SELECT * FROM check_test(
        has_inherited_tables( 'hide'::name, 'h_parent'::name )
@@ -131,8 +130,6 @@ SELECT * FROM check_test(
        , 'hide.h_child1 inherits from hide.h_parent'
 );
 
-
-
 /****************************************************************************/
 -- Finish the tests and clean up.
 SELECT * FROM finish();
```

**Pull request closed without merging**
